"use client";

import Link from "next/link";
import { Button } from "@/components/ui/button";
import { FieldLabel } from "@/components/ui/chassis";
import { Roundel } from "@/components/ui/roundel";
import { useCurrentUser } from "@/hooks/use-current-user";

interface Props {
  skipReason: string | null;
}

/**
 * Renders when the roadmap generation was skipped — typically because the
 * user had no token budget left. FREE users get a direct path to /pricing;
 * PRO users are told what to do (contact us). Never invent a client-side
 * retry — the artifact is only regenerated by the server.
 */
export function RoadmapSkipped({ skipReason }: Props) {
  const me = useCurrentUser();
  const plan = me.data?.planTier ?? null;
  const isFree = plan === "FREE";

  const reasonText =
    skipReason ??
    "There weren’t enough tokens available when this playlist finished indexing, so the route was never laid out.";

  return (
    <section className="relative overflow-hidden rounded-[var(--radius-chassis)] border border-dashed border-[var(--color-border)] bg-[var(--color-surface)] p-8">
      <div aria-hidden className="enamel-watermark absolute inset-0" />
      <div className="relative mx-auto flex max-w-md flex-col items-center gap-4 text-center">
        <Roundel size={44} className="text-[var(--color-fg-muted)]" />
        <div className="space-y-2">
          <FieldLabel>Route not built</FieldLabel>
          <h2 className="font-display text-lg font-semibold text-[var(--color-fg)]">
            This playlist has no roadmap
          </h2>
          <p className="text-sm leading-relaxed text-[var(--color-fg-muted)]">{reasonText}</p>
        </div>

        {isFree && (
          <div className="w-full space-y-3 pt-2">
            <p className="text-xs leading-relaxed text-[var(--color-fg-muted)]">
              Pro lifts your token cap, so roadmaps get built for playlists you
              add from then on.
            </p>
            <Button asChild variant="primary" size="md" className="w-full">
              <Link href="/pricing">See Pro plans</Link>
            </Button>
          </div>
        )}
        {plan === "PRO" && (
          <p className="pt-2 text-xs leading-relaxed text-[var(--color-fg-muted)]">
            You’re on Pro — if this looks wrong, contact support and include the
            source id from this page’s address.
          </p>
        )}
      </div>
    </section>
  );
}
