import { createHash } from 'node:crypto';

import { throwIngestionError } from '@/inngest/errors.js';
import { fetchYouTubeVideo } from '@/integrations/youtube.js';

import type { ExtractedSegment, ExtractionResult, Extractor, ExtractorSource } from './types.js';

export class YouTubeExtractor implements Extractor {
  async extract(source: ExtractorSource): Promise<ExtractionResult> {
    const videoId = resolveVideoId(source);
    const data = await fetchYouTubeVideo(videoId);
    const segments: ExtractedSegment[] = data.cues.map((cue) => ({
      text: cue.text,
      locator: {
        kind: 'timestamp',
        startMs: cue.startMs,
        endMs: cue.endMs,
        videoId: data.videoId,
      },
    }));
    const canonical = data.cues.map((c) => `${c.startMs}\t${c.endMs}\t${c.text}`).join('\n');
    return {
      title: data.title,
      segments,
      metadata: {
        videoId: data.videoId,
        channelId: data.channelId,
        channelName: data.channelName,
        durationSec: data.durationSec,
        transcriptLanguage: data.transcriptLanguage,
        transcriptAutoGenerated: data.transcriptAutoGenerated,
        cueCount: data.cues.length,
      },
      contentHash: createHash('sha256').update(canonical, 'utf8').digest('hex'),
    };
  }
}

function resolveVideoId(source: ExtractorSource): string {
  const candidate = source.mediaId ?? source.originalRef;
  const idRe = /^[A-Za-z0-9_-]{11}$/;
  if (idRe.test(candidate)) return candidate;

  try {
    const url = new URL(candidate);
    const v = url.searchParams.get('v');
    if (v && idRe.test(v)) return v;

    const path = url.pathname.replace(/^\/+/, '').split('/').filter(Boolean);
    for (const part of path) {
      const segment = part.split('?')[0]?.split('&')[0] ?? '';
      if (idRe.test(segment)) return segment;
    }
  } catch {
    // fall through to ingestion error below
  }

  throwIngestionError(
    'EXTRACTION_FAILED',
    `Cannot resolve a YouTube video id from source ${source.id}.`,
  );
}

export const youtubeExtractor = new YouTubeExtractor();
