import { google, type youtube_v3 } from 'googleapis';
import {
  fetchTranscript,
  type TranscriptResponse,
  YoutubeTranscriptDisabledError,
  YoutubeTranscriptNotAvailableError,
  YoutubeTranscriptNotAvailableLanguageError,
  YoutubeTranscriptTooManyRequestError,
  YoutubeTranscriptVideoUnavailableError,
} from 'youtube-transcript';

import { env } from '@/config/env.js';
import { throwIngestionError } from '@/inngest/errors.js';
import { logger } from '@/observability/logger.js';

import { withTimeout } from './runtime.js';

const REQUEST_TIMEOUT_MS = 20_000;
const PLAYLIST_PAGE_SIZE = 50;

let youtubeClient: youtube_v3.Youtube | null = null;

function getClient(): youtube_v3.Youtube {
  if (youtubeClient) return youtubeClient;
  const apiKey = env.YOUTUBE_API_KEY;
  if (!apiKey) {
    throwIngestionError(
      'EXTRACTION_FAILED',
      'YOUTUBE_API_KEY is not configured; cannot call the YouTube Data API.',
    );
  }
  youtubeClient = google.youtube({ version: 'v3', auth: apiKey });
  return youtubeClient;
}

export interface YouTubeTranscriptCue {
  startMs: number;
  endMs: number;
  text: string;
}

export interface YouTubeVideoMetadata {
  videoId: string;
  title: string;
  channelId: string | null;
  channelName: string | null;
  durationSec: number | null;
  transcriptLanguage: string | null;
  transcriptAutoGenerated: boolean | null;
}

export interface YouTubeVideoData extends YouTubeVideoMetadata {
  cues: YouTubeTranscriptCue[];
}

export async function fetchYouTubeVideo(videoId: string): Promise<YouTubeVideoData> {
  const meta = await fetchVideoMetadata(videoId);

  let raw: TranscriptResponse[];
  try {
    raw = await withTimeout('YouTube fetchTranscript', REQUEST_TIMEOUT_MS, () =>
      fetchTranscript(videoId),
    );
  } catch (err) {
    handleTranscriptError(err, videoId);
  }

  const cues = normalizeCueUnits(raw, meta.durationSec);
  if (cues.length === 0) {
    throwIngestionError('TRANSCRIPT_DISABLED', `Video ${videoId} has no transcript cues.`);
  }

  const language = raw.find((c) => typeof c.lang === 'string' && c.lang.length > 0)?.lang ?? null;
  return {
    ...meta,
    transcriptLanguage: language,

    transcriptAutoGenerated: null,
    cues,
  };
}

async function fetchVideoMetadata(videoId: string): Promise<YouTubeVideoMetadata> {
  const client = getClient();
  let response;
  try {
    response = await withTimeout('YouTube videos.list', REQUEST_TIMEOUT_MS, () =>
      client.videos.list({
        part: ['snippet', 'contentDetails', 'status'],
        id: [videoId],
        maxResults: 1,
      }),
    );
  } catch (err) {
    handleGoogleApiError(err, `videos.list ${videoId}`);
  }
  const item = response.data.items?.[0];
  if (!item) {
    throwIngestionError(
      'EXTRACTION_FAILED',
      `Video ${videoId} is unavailable, removed, or does not exist.`,
    );
  }
  const privacy = item.status?.privacyStatus ?? null;
  if (privacy === 'private') {
    throwIngestionError('EXTRACTION_FAILED', `Video ${videoId} is private.`);
  }
  return {
    videoId,
    title: item.snippet?.title ?? videoId,
    channelId: item.snippet?.channelId ?? null,
    channelName: item.snippet?.channelTitle ?? null,
    durationSec: parseIso8601Duration(item.contentDetails?.duration ?? null),
    transcriptLanguage: null,
    transcriptAutoGenerated: null,
  };
}

export function normalizeCueUnits(
  raw: readonly TranscriptResponse[],
  videoDurationSec: number | null,
): YouTubeTranscriptCue[] {
  if (raw.length === 0) return [];
  let anyFractional = false;
  let maxOffset = 0;
  for (const r of raw) {
    if (!Number.isInteger(r.offset) || !Number.isInteger(r.duration)) {
      anyFractional = true;
    }
    if (r.offset > maxOffset) maxOffset = r.offset;
  }
  const inSeconds =
    anyFractional || (videoDurationSec !== null && maxOffset <= videoDurationSec + 60);
  const scale = inSeconds ? 1000 : 1;
  const cues: YouTubeTranscriptCue[] = [];
  for (const r of raw) {
    const text = r.text.trim();
    if (text.length === 0) continue;
    const startMs = Math.round(r.offset * scale);
    const endMs = Math.round((r.offset + r.duration) * scale);
    cues.push({ startMs, endMs, text });
  }
  return cues;
}

export function parseIso8601Duration(v: string | null): number | null {
  if (v === null) return null;
  const m = /^P(?:(\d+)D)?T?(?:(\d+)H)?(?:(\d+)M)?(?:(\d+(?:\.\d+)?)S)?$/i.exec(v.trim());
  if (!m) return null;
  const days = m[1] ? Number(m[1]) : 0;
  const hours = m[2] ? Number(m[2]) : 0;
  const minutes = m[3] ? Number(m[3]) : 0;
  const seconds = m[4] ? Number(m[4]) : 0;
  const total = days * 86_400 + hours * 3600 + minutes * 60 + seconds;
  return Number.isFinite(total) ? total : null;
}

function handleTranscriptError(err: unknown, videoId: string): never {
  if (
    err instanceof YoutubeTranscriptDisabledError ||
    err instanceof YoutubeTranscriptNotAvailableError ||
    err instanceof YoutubeTranscriptNotAvailableLanguageError
  ) {
    throwIngestionError(
      'TRANSCRIPT_DISABLED',
      `Video ${videoId} has no usable transcript: ${err.message}.`,
      { cause: err },
    );
  }
  if (err instanceof YoutubeTranscriptVideoUnavailableError) {
    throwIngestionError('EXTRACTION_FAILED', `Video ${videoId} is unavailable: ${err.message}.`, {
      cause: err,
    });
  }
  if (err instanceof YoutubeTranscriptTooManyRequestError) {
    throwIngestionError('NETWORK_ERROR', `YouTube transcript scraper rate-limited on ${videoId}.`, {
      cause: err,
    });
  }
  const msg = err instanceof Error ? err.message : String(err);
  if (/age.?restrict|sign.?in/i.test(msg)) {
    throwIngestionError(
      'PERMISSION_DENIED',
      `Video ${videoId} requires sign-in (age-restricted).`,
      { cause: err },
    );
  }
  if (/timeout/i.test(msg) || /ETIMEDOUT|ECONNRESET/i.test(msg)) {
    throwIngestionError('NETWORK_ERROR', `YouTube transcript network error on ${videoId}.`, {
      cause: err,
    });
  }
  logger.warn({ videoId, err: msg }, 'Unclassified YouTube transcript error');
  throwIngestionError('TRANSCRIPT_DISABLED', `Video ${videoId} transcript fetch failed: ${msg}.`, {
    cause: err,
  });
}

function handleGoogleApiError(err: unknown, label: string): never {
  const status =
    (err as { code?: number; response?: { status?: number } }).code ??
    (err as { response?: { status?: number } }).response?.status ??
    null;
  const msg = err instanceof Error ? err.message : String(err);
  if (status === 404) {
    throwIngestionError('EXTRACTION_FAILED', `${label}: not found.`, { cause: err });
  }
  if (status === 403) {
    throwIngestionError(
      'PERMISSION_DENIED',
      `${label}: forbidden (${msg}). Check YOUTUBE_API_KEY quota and referrer restrictions.`,
      { cause: err },
    );
  }
  if (status !== null && status >= 500) {
    throwIngestionError('NETWORK_ERROR', `${label}: upstream ${status}.`, { cause: err });
  }
  if (/timeout/i.test(msg) || /ETIMEDOUT|ECONNRESET|ENOTFOUND/i.test(msg)) {
    throwIngestionError('NETWORK_ERROR', `${label}: network error (${msg}).`, { cause: err });
  }
  throwIngestionError('EXTRACTION_FAILED', `${label}: ${msg}.`, { cause: err });
}

export interface YouTubePlaylistItem {
  videoId: string;
  title: string;
  durationSec: number | null;
}

export interface YouTubePlaylistData {
  playlistId: string;
  title: string;
  channelName: string | null;
  totalItems: number;
  items: YouTubePlaylistItem[];
}

export async function fetchYouTubePlaylist(
  playlistId: string,
  maxItems: number,
): Promise<YouTubePlaylistData> {
  const client = getClient();

  let playlistResponse;
  try {
    playlistResponse = await withTimeout('YouTube playlists.list', REQUEST_TIMEOUT_MS, () =>
      client.playlists.list({
        part: ['snippet', 'contentDetails'],
        id: [playlistId],
        maxResults: 1,
      }),
    );
  } catch (err) {
    handleGoogleApiError(err, `playlists.list ${playlistId}`);
  }
  const playlistMeta = playlistResponse.data.items?.[0];
  if (!playlistMeta) {
    throwIngestionError(
      'EXTRACTION_FAILED',
      `Playlist ${playlistId} is unavailable, private, or does not exist.`,
    );
  }

  const items: YouTubePlaylistItem[] = [];
  let pageToken: string | undefined;
  do {
    let itemsResponse;
    try {
      itemsResponse = await withTimeout('YouTube playlistItems.list', REQUEST_TIMEOUT_MS, () =>
        client.playlistItems.list({
          part: ['snippet', 'contentDetails', 'status'],
          playlistId,
          maxResults: PLAYLIST_PAGE_SIZE,
          ...(pageToken !== undefined ? { pageToken } : {}),
        }),
      );
    } catch (err) {
      handleGoogleApiError(err, `playlistItems.list ${playlistId}`);
    }
    for (const item of itemsResponse.data.items ?? []) {
      collectPlaylistItem(item, items);
      if (items.length >= maxItems) break;
    }
    pageToken = itemsResponse.data.nextPageToken ?? undefined;
  } while (pageToken !== undefined && items.length < maxItems);

  const total = playlistMeta.contentDetails?.itemCount ?? items.length;
  return {
    playlistId,
    title: playlistMeta.snippet?.title ?? playlistId,
    channelName: playlistMeta.snippet?.channelTitle ?? null,
    totalItems: total,
    items: items.slice(0, maxItems),
  };
}

function collectPlaylistItem(
  item: youtube_v3.Schema$PlaylistItem,
  out: YouTubePlaylistItem[],
): void {
  const videoId = item.contentDetails?.videoId ?? item.snippet?.resourceId?.videoId ?? null;
  if (!videoId || !/^[A-Za-z0-9_-]{11}$/.test(videoId)) return;
  const privacy = item.status?.privacyStatus ?? null;

  if (privacy === 'private' || privacy === 'privacyStatusUnspecified') return;
  const title = item.snippet?.title ?? videoId;
  if (title === 'Private video' || title === 'Deleted video') return;
  out.push({ videoId, title, durationSec: null });
}

export function __setYouTubeClientForTests(fake: youtube_v3.Youtube | null): void {
  youtubeClient = fake;
}
