/**
 * YouTube caption retrieval.
 *
 * Why the Data API cannot do this on its own: `captions.list` accepts an API key
 * and reports which caption tracks a video publishes, but `captions.download`
 * rejects API keys outright — it answers
 *   401 "API keys are not supported by this API"
 * and only accepts an OAuth token belonging to the *video owner*. So
 * YOUTUBE_API_KEY can tell us whether captions exist, never hand us their text
 * for a video we do not own. `youtube.ts` uses it for exactly that: to decide
 * whether a failed fetch is terminal ("this video has no captions") or transient
 * ("captions exist, we were blocked") — see `listCaptionTracks` there.
 *
 * How we get the text instead: we ask YouTube's own player endpoint (InnerTube,
 * `/youtubei/v1/player`) for the caption track list and download the track from
 * the `timedtext` URL it returns. That is the request the mobile apps make, so it
 * never touches the watch-page HTML that the `youtube-transcript` package
 * scraped — and the watch page is what serves a consent/bot-check interstitial
 * to datacenter IPs, which is why transcript ingestion failed in production but
 * worked from a laptop.
 *
 * Each client in INNERTUBE_CLIENTS is tried in turn; they fail independently, so
 * the chain survives any one of them being throttled or retired.
 *
 * The hard limit: YouTube gates InnerTube on IP reputation, and answers requests
 * from datacenter ranges (AWS/GCP/Azure/most VPS hosts) with a bot check —
 * playabilityStatus LOGIN_REQUIRED, reason "Sign in to confirm you're not a bot".
 * That is *not* an age gate, and treating it as one parks a perfectly ingestible
 * video in a permanent failure state; see `isBotCheck` below and the BOT_CHECK
 * branch in `youtube.ts`. No client, visitorData, or PO token reliably avoids it
 * from a datacenter IP, so `YOUTUBE_PROXY_URL` exists to send just these requests
 * (not the rest of the app's egress) through a residential proxy.
 */

import { ProxyAgent } from 'undici';

import { env } from '@/config/env.js';

const INNERTUBE_URL = 'https://www.youtube.com/youtubei/v1/player?prettyPrint=false';
const REQUEST_TIMEOUT_MS = 20_000;

/** Fallback cue length when a caption event carries no duration. */
const DEFAULT_CUE_MS = 3_000;

/**
 * Track languages we prefer when a video publishes several. A manually authored
 * track wins over an auto-generated (ASR) one in the same language; if none of
 * these languages is present we fall back to the video's own first track.
 */
const PREFERRED_LANGUAGES = ['en'] as const;

interface InnertubeClient {
  readonly id: string;
  readonly clientName: string;
  readonly clientNumber: string;
  readonly clientVersion: string;
  readonly extraContext: Readonly<Record<string, unknown>>;
  readonly userAgent: string;
}

const INNERTUBE_CLIENTS: readonly InnertubeClient[] = [
  {
    id: 'ANDROID',
    clientName: 'ANDROID',
    clientNumber: '3',
    clientVersion: '20.10.38',
    extraContext: { androidSdkVersion: 30, osName: 'Android', osVersion: '11' },
    userAgent: 'com.google.android.youtube/20.10.38 (Linux; U; Android 11) gzip',
  },
  {
    id: 'IOS',
    clientName: 'IOS',
    clientNumber: '5',
    clientVersion: '20.10.4',
    extraContext: {
      deviceMake: 'Apple',
      deviceModel: 'iPhone16,2',
      osName: 'iPhone',
      osVersion: '18.3.2.22D82',
    },
    userAgent: 'com.google.ios.youtube/20.10.4 (iPhone16,2; U; CPU iOS 18_3_2 like Mac OS X)',
  },
];

/**
 * Clients deliberately absent, all measured against a known-good captioned video
 * from an unblocked residential IP:
 *   ANDROID_VR                      bot check, even unblocked — permanently dead
 *   TVHTML5, WEB, MWEB              require a PO token; answer "reloaded"/unavailable
 *   WEB_EMBEDDED_PLAYER, TVHTML5_SIMPLY_EMBEDDED_PLAYER
 *                                   answer ERROR regardless of video
 * Attaching visitorData revived none of them. Keeping a dead client in the chain
 * costs a round trip and, worse, contributes a spurious LOGIN_REQUIRED to the
 * evidence the caller classifies on.
 */

export interface CaptionCue {
  startMs: number;
  endMs: number;
  text: string;
}

export interface CaptionTrack {
  baseUrl?: string;
  kind?: string;
  languageCode?: string;
  vssId?: string;
}

/**
 * Why a caption fetch produced nothing. Deliberately descriptive rather than
 * pre-classified: `youtube.ts` turns these into ingestion failure codes, because
 * only it can consult the Data API to tell "no captions exist" (terminal) apart
 * from "we were blocked" (retryable).
 */
export type CaptionFailureReason =
  | 'BOT_CHECK'
  | 'LOGIN_REQUIRED'
  | 'NO_CAPTION_TRACKS'
  | 'UNREACHABLE'
  | 'VIDEO_UNAVAILABLE';

export type CaptionOutcome =
  | {
      ok: true;
      client: string;
      cues: CaptionCue[];
      languageCode: string | null;
      autoGenerated: boolean;
    }
  | { ok: false; reason: CaptionFailureReason; detail: string };

/**
 * YouTube reports its bot check as LOGIN_REQUIRED, the same status it uses for
 * genuinely age-restricted and members-only videos — but the two mean opposite
 * things to us. A bot check says nothing about the video (it is about our IP's
 * reputation) and clears on its own; an age gate is a permanent property of the
 * video. Only the reason string separates them, so match on it.
 *
 * Note the apostrophe: YouTube sends U+2019 ("you\u2019re"), not an ASCII quote.
 * Matching "not a bot" sidesteps the distinction entirely.
 */
export function isBotCheck(reason: string): boolean {
  return /not a bot|confirm you.{0,3}re not|unusual traffic|automated queries/i.test(reason);
}

interface PlayerResponse {
  captions?: {
    playerCaptionsTracklistRenderer?: {
      captionTracks?: CaptionTrack[];
    };
  };
  playabilityStatus?: { status?: string; reason?: string };
}

let proxyAgent: ProxyAgent | null = null;
let proxyAgentUrl: string | null = null;

/**
 * Send YouTube traffic through YOUTUBE_PROXY_URL when one is configured.
 *
 * Scoped to this module on purpose. A residential proxy is metered and slow, and
 * the bot check only applies to YouTube — routing the app's other egress (OpenAI,
 * Qdrant, Clerk, Firecrawl) through it via a global HTTPS_PROXY would burn the
 * quota on traffic that was never blocked.
 */
function proxyDispatcher(): ProxyAgent | undefined {
  const url = env.YOUTUBE_PROXY_URL;
  if (!url) return undefined;
  if (!proxyAgent || proxyAgentUrl !== url) {
    proxyAgent = new ProxyAgent(url);
    proxyAgentUrl = url;
  }
  return proxyAgent;
}

/**
 * Attach the proxy dispatcher to a fetch init.
 *
 * The cast is unavoidable and deliberately quarantined here: `undici` ships its
 * own Dispatcher types while @types/node carries a separate `undici-types` copy,
 * so the two ProxyAgent shapes are structurally identical but nominally
 * incompatible. Keeping the cast in one helper leaves every call site's init
 * object fully type-checked.
 */
function withProxy(init: RequestInit): RequestInit {
  const dispatcher = proxyDispatcher();
  if (!dispatcher) return init;
  return { ...init, dispatcher } as unknown as RequestInit;
}

/** True when captions are being fetched through a proxy — for log context only. */
export function isProxied(): boolean {
  return Boolean(env.YOUTUBE_PROXY_URL);
}

/**
 * Fetch the best caption track for a video, trying each InnerTube client in turn.
 * Never throws: every failure path returns `{ ok: false }` so the caller can
 * classify it with the extra evidence only it has.
 */
export async function fetchCaptionCues(videoId: string): Promise<CaptionOutcome> {
  const attempts: string[] = [];
  let sawBotCheck = false;
  let sawEmptyTrackList = false;
  let sawLoginRequired = false;
  let sawUnavailable = false;

  for (const client of INNERTUBE_CLIENTS) {
    let payload: PlayerResponse;
    try {
      payload = await requestPlayer(videoId, client);
    } catch (err) {
      attempts.push(`${client.id}: ${errorMessage(err)}`);
      continue;
    }

    const status = payload.playabilityStatus?.status ?? 'UNKNOWN';
    const reason = payload.playabilityStatus?.reason ?? '';
    if (status === 'LOGIN_REQUIRED' && isBotCheck(reason)) {
      sawBotCheck = true;
      attempts.push(`${client.id}: BOT_CHECK (${reason})`);
      continue;
    }
    if (status === 'LOGIN_REQUIRED' || status === 'AGE_VERIFICATION_REQUIRED') {
      sawLoginRequired = true;
      attempts.push(`${client.id}: ${status} (${reason})`);
      continue;
    }

    const tracks = payload.captions?.playerCaptionsTracklistRenderer?.captionTracks ?? [];
    if (tracks.length === 0) {
      if (status === 'OK') {
        // A playable video that lists no tracks is real evidence of "no captions".
        sawEmptyTrackList = true;
        attempts.push(`${client.id}: playable but publishes no caption tracks`);
      } else {
        sawUnavailable = true;
        attempts.push(`${client.id}: ${status} (${reason})`);
      }
      continue;
    }

    const track = selectCaptionTrack(tracks);
    if (!track?.baseUrl) {
      attempts.push(`${client.id}: ${tracks.length} track(s) but none had a download URL`);
      continue;
    }

    try {
      const cues = await downloadCaptionTrack(track.baseUrl, client.userAgent);
      if (cues.length === 0) {
        attempts.push(`${client.id}: track ${track.languageCode ?? '?'} downloaded empty`);
        continue;
      }
      return {
        ok: true,
        client: client.id,
        cues,
        languageCode: track.languageCode ?? null,
        autoGenerated: track.kind === 'asr',
      };
    } catch (err) {
      attempts.push(`${client.id}: timedtext ${errorMessage(err)}`);
    }
  }

  const detail = attempts.join('; ');
  // Ordered by how much each answer tells us about the *video* rather than about
  // us. "Playable, no tracks" and a real sign-in gate are facts about the video,
  // so they outrank a bot check, which is only a fact about our IP this minute.
  if (sawEmptyTrackList) return { ok: false, reason: 'NO_CAPTION_TRACKS', detail };
  if (sawLoginRequired) return { ok: false, reason: 'LOGIN_REQUIRED', detail };
  if (sawBotCheck) return { ok: false, reason: 'BOT_CHECK', detail };
  if (sawUnavailable) return { ok: false, reason: 'VIDEO_UNAVAILABLE', detail };
  return { ok: false, reason: 'UNREACHABLE', detail };
}

async function requestPlayer(videoId: string, client: InnertubeClient): Promise<PlayerResponse> {
  const res = await fetch(INNERTUBE_URL, withProxy({
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Accept-Language': 'en-US,en;q=0.9',
      'User-Agent': client.userAgent,
      'X-Youtube-Client-Name': client.clientNumber,
      'X-Youtube-Client-Version': client.clientVersion,
      Origin: 'https://www.youtube.com',
    },
    body: JSON.stringify({
      videoId,
      contentCheckOk: true,
      racyCheckOk: true,
      context: {
        client: {
          ...client.extraContext,
          clientName: client.clientName,
          clientVersion: client.clientVersion,
          gl: 'US',
          hl: 'en',
          userAgent: client.userAgent,
        },
      },
    }),
    signal: AbortSignal.timeout(REQUEST_TIMEOUT_MS),
  }));
  if (!res.ok) {
    throw new Error(`player endpoint responded ${res.status}`);
  }
  return (await res.json()) as PlayerResponse;
}

async function downloadCaptionTrack(baseUrl: string, userAgent: string): Promise<CaptionCue[]> {
  // Some clients hand back a baseUrl that already pins `fmt`; overwrite rather
  // than append, or YouTube keeps serving its original format.
  const url = new URL(baseUrl);
  url.searchParams.set('fmt', 'json3');
  const res = await fetch(url, withProxy({
    headers: { 'Accept-Language': 'en-US,en;q=0.9', 'User-Agent': userAgent },
    // The timedtext URL is issued to whoever asked the player for it, so it has
    // to be fetched over the same egress path.
    signal: AbortSignal.timeout(REQUEST_TIMEOUT_MS),
  }));
  if (!res.ok) {
    throw new Error(`responded ${res.status}`);
  }
  return parseTimedText(await res.text());
}

/**
 * Pick a track: preferred language (manual before auto-generated), otherwise the
 * first manually authored track, otherwise whatever the video has.
 */
export function selectCaptionTrack(tracks: readonly CaptionTrack[]): CaptionTrack | null {
  const usable = tracks.filter((t) => typeof t.baseUrl === 'string' && t.baseUrl.length > 0);
  if (usable.length === 0) return null;
  for (const lang of PREFERRED_LANGUAGES) {
    const inLang = usable.filter((t) => baseLanguage(t.languageCode) === lang);
    const manual = inLang.find((t) => t.kind !== 'asr');
    if (manual) return manual;
    if (inLang[0]) return inLang[0];
  }
  return usable.find((t) => t.kind !== 'asr') ?? usable[0] ?? null;
}

function baseLanguage(code: string | undefined): string {
  return (code ?? '').toLowerCase().split('-')[0] ?? '';
}

/** Parse a timedtext body, accepting either the json3 or the XML (srv1/srv3) shape. */
export function parseTimedText(body: string): CaptionCue[] {
  const trimmed = body.trim();
  if (trimmed.length === 0) return [];
  if (trimmed.startsWith('<')) return parseTimedTextXml(trimmed);
  return parseJson3(trimmed);
}

interface Json3Event {
  aAppend?: number;
  dDurationMs?: number;
  segs?: { utf8?: string }[];
  tStartMs?: number;
}

export function parseJson3(body: string): CaptionCue[] {
  let parsed: { events?: Json3Event[] };
  try {
    parsed = JSON.parse(body) as { events?: Json3Event[] };
  } catch {
    return [];
  }
  const cues: CaptionCue[] = [];
  for (const event of parsed.events ?? []) {
    // Rolling auto-captions repeat the previous line with aAppend=1; keeping them
    // would duplicate most of the transcript.
    if (event.aAppend === 1) continue;
    if (!Array.isArray(event.segs)) continue;
    const text = collapseWhitespace(event.segs.map((s) => s.utf8 ?? '').join(''));
    if (text.length === 0) continue;
    const startMs = Math.max(0, Math.round(event.tStartMs ?? 0));
    const durationMs = Math.max(0, Math.round(event.dDurationMs ?? 0));
    cues.push({ startMs, endMs: startMs + durationMs, text });
  }
  return fillMissingEnds(cues);
}

const XML_P_RE = /<p\b([^>]*)>([\s\S]*?)<\/p>/g;
const XML_TEXT_RE = /<text\b([^>]*)>([\s\S]*?)<\/text>/g;

export function parseTimedTextXml(body: string): CaptionCue[] {
  const cues: CaptionCue[] = [];
  // srv3 (`<p t="ms" d="ms">`) first; srv1 (`<text start="s" dur="s">`) as fallback.
  for (const match of body.matchAll(XML_P_RE)) {
    const attrs = match[1] ?? '';
    const startMs = Math.max(0, Math.round(numericAttr(attrs, 't') ?? 0));
    const durationMs = Math.max(0, Math.round(numericAttr(attrs, 'd') ?? 0));
    pushXmlCue(cues, startMs, durationMs, match[2] ?? '');
  }
  if (cues.length > 0) return fillMissingEnds(cues);
  for (const match of body.matchAll(XML_TEXT_RE)) {
    const attrs = match[1] ?? '';
    const startMs = Math.max(0, Math.round((numericAttr(attrs, 'start') ?? 0) * 1000));
    const durationMs = Math.max(0, Math.round((numericAttr(attrs, 'dur') ?? 0) * 1000));
    pushXmlCue(cues, startMs, durationMs, match[2] ?? '');
  }
  return fillMissingEnds(cues);
}

function pushXmlCue(cues: CaptionCue[], startMs: number, durationMs: number, inner: string): void {
  // srv3 wraps words in <s> elements; strip any inner markup before decoding.
  const text = collapseWhitespace(decodeEntities(inner.replace(/<[^>]*>/g, '')));
  if (text.length === 0) return;
  cues.push({ startMs, endMs: startMs + durationMs, text });
}

function numericAttr(attrs: string, name: string): number | null {
  const m = new RegExp(`\\b${name}="([^"]*)"`).exec(attrs);
  if (!m?.[1]) return null;
  const n = Number(m[1]);
  return Number.isFinite(n) ? n : null;
}

/** Give zero-length cues an end: the next cue's start, or a default span. */
function fillMissingEnds(cues: CaptionCue[]): CaptionCue[] {
  for (let i = 0; i < cues.length; i += 1) {
    const cue = cues[i];
    if (!cue || cue.endMs > cue.startMs) continue;
    const next = cues[i + 1];
    cue.endMs =
      next && next.startMs > cue.startMs
        ? next.startMs
        : cue.startMs + DEFAULT_CUE_MS;
  }
  return cues;
}

const NAMED_ENTITIES: Readonly<Record<string, string>> = {
  amp: '&',
  apos: "'",
  gt: '>',
  lt: '<',
  nbsp: ' ',
  quot: '"',
};

function decodeEntitiesOnce(input: string): string {
  return input.replace(/&(#x?[0-9a-f]+|[a-z]+);/gi, (whole, body: string) => {
    if (body.startsWith('#')) {
      const code = body[1] === 'x' || body[1] === 'X' ? parseInt(body.slice(2), 16) : Number(body.slice(1));
      return Number.isFinite(code) && code > 0 ? String.fromCodePoint(code) : whole;
    }
    return NAMED_ENTITIES[body.toLowerCase()] ?? whole;
  });
}

/** YouTube double-encodes some caption text (`&amp;#39;`), so decode twice. */
function decodeEntities(input: string): string {
  return decodeEntitiesOnce(decodeEntitiesOnce(input));
}

function collapseWhitespace(input: string): string {
  return input.replace(/\s+/g, ' ').trim();
}

function errorMessage(err: unknown): string {
  if (err instanceof Error) {
    return err.name === 'TimeoutError' || err.name === 'AbortError' ? 'timed out' : err.message;
  }
  return String(err);
}
